na4zagin3/satyrographos

- bin/main.ml
- src/satysfiDirs.ml
- src/store.ml
> Support other libroots

- bin/main.ml
> Fix default install directory with SATYSFI_RUNTIME

- src/buildScript.ml
Required by #32 and #13.
Example:
```lisp
(package
(name "grcnum")
(sources
((package "grcnum.satyh" "./grcnum.satyh")))
(opam "satysfi-grcnum.opam")
(dependencies ((fonts-theano ())))) ;; <-- this section
```
> Add dependencies field to build file

- bin/commandInstall.ml
> Install transitive dependencies

- src/buildScript.ml
> Add version section to build file

- src/buildScript.ml
> Change accepted build file version to 0.0.2

- src/buildScript.ml
- src/library.ml
> Add version field

- bin/commandInstall.ml
- bin/commandLibrary.ml
- bin/commandOpam.ml
- bin/commandPin.ml
- bin/commandStatus.ml
- bin/setup.ml
> Avoid writing ~/.satyrographos unless it is required

- satyrographos.opam
See https://github.com/ocaml/opam-repository/pull/14266
> Fix dependency on dune

- satyrographos.opam
Cf. https://spdx.org/licenses/
> Use SPDX licence identifier

- bin/dune
- src/satysfiDirs.ml
- src/store.ml
See https://github.com/ocaml/opam-repository/pull/15469.
> Update for core v0.13.

- .travis.yml
- bin/commandPin.ml
- bin/dune
- satyrographos.opam
> Feature/core v0.13

- bin/commandInstall.ml
> Fix missing a line break from a log

- CHANGELOG.md
- bin/main.ml
- satyrographos.opam
Bump version and update CHANGELOG
> Bump version to 0.0.2.2

- bin/commandOpam.ml
- src/commandOpam.ml
Refactoring CommandOpam for unit testing (#19).
> Refactor CommandOpam with moving script loading logic

- test/testcases/dune
- test/testcases/install_l__dependent.expected
- test/testcases/install_l__dependent.ml
- test/testcases/install_l__independentTwo.expected
- test/testcases/install_l__independentTwo.ml
- test/testcases/install_l__simple.expected
- test/testcases/install_l__simple.ml
- test/testcases/install_l__transitive.expected
- test/testcases/install_l__transitive.ml
- test/testcases/prepareOpamReg.ml
> Add test cases for install subcommand with option -l

- bin/commandPin.ml
- bin/dune
- bin/setup.ml
- bin/setup.mli
- src/Environment.mli
- src/commandPin.ml
- src/commandPin.mli
This PR refactors bin/commandPin.ml and add a few .mli files.
Part of #19.
>  Refactor bin/commandPin.ml

- bin/setup.mli
- src/buildScript.ml
- test/testcases/opam_install__library.expected
- test/testcases/opam_install__library.ml
Fixes https://github.com/na4zagin3/satyrographos/issues/93
> Fix a bug preventing using (file ...) section

- src/commandInstall.ml
- test/testcases/dune
- test/testcases/install__twoDists.expected
- test/testcases/install__twoDists.ml
> Test if user installed dist overrides system one

- src/commandInstall.ml
- src/commandOpam.ml
- test/testcases/install__onlyDist.expected
- test/testcases/install__thirdParties.expected
- test/testcases/install_l__dependent.expected
- test/testcases/install_l__independentTwo.expected
- test/testcases/install_l__simple.expected
- test/testcases/install_l__transitive.expected
- test/testcases/opam_build__doc_satysfi.expected
This fixes weird messages. This PR also removes output from satysfi triggered for option check.
> Insert a line break in verbose messages

- README-ja.md
- README.md
- src/buildScript.ml
- test/testcases/dune
- test/testcases/opam_install__library_recursive.expected
- test/testcases/opam_install__library_recursive.ml
This PR adds `(fontDir <dir>)` and `(packageDir <dir>)`.
Closes #64
> Add packageDir and fontDir to add packages/fonts recursively

- bin/setup.ml
- src/opamSatysfiRegistry.ml
- test/testcases/install__emptyDist.ml
- test/testcases/install__missingDist.ml
- test/testcases/install__onlyDist.ml
- test/testcases/install__thirdParties.ml
- test/testcases/install__thirdParties_brokenDependency.ml
- test/testcases/install__twoDists.ml
- test/testcases/install_l__dependent.ml
- test/testcases/install_l__independentTwo.ml
- test/testcases/install_l__simple.ml
- test/testcases/install_l__thirdParties_brokenDependency.ml
- test/testcases/install_l__transitive.ml
- test/testcases/opam_build__doc_satysfi.ml
- test/testcases/opam_install__doc.ml
- test/testcases/opam_install__library.ml
- test/testcases/opam_install__library_missingHash.ml
- test/testcases/opam_install__library_missingPackage.ml
- test/testcases/opam_install__library_recursive.ml
- test/testcases/testLib.ml
- test/testcases/testLib.mli
> Stop reading reg_opam when the directory does not exist

- CHANGELOG.md
- bin/main.ml
- satyrographos.opam
This PR changes version numbers and update CHANGELOG.
> Prepare release v0.0.2.3

- bin/commandLibrary.ml
- src/commandInstall.ml
- src/library.ml
- src/registry.ml
- src/repository.ml
- test/testcases/dune
- test/testcases/install__distWithNonHashUnderHashDir.expected
- test/testcases/install__distWithNonHashUnderHashDir.ml
Fixes https://github.com/na4zagin3/satyrographos/issues/110.
> Show a warning message instead of failing with non-hash files in hash dir

- src/commandInstall.ml
- src/library.ml
- src/library.mli
> Refactoring: Add library.mli

- bin/commandInstall.ml
- bin/commandOpam.ml
- bin/commandPin.ml
- bin/dune
- src/command/dune
- src/command/install.ml
- src/command/opam.ml
- src/command/pin.ml
- src/command/pin.mli
- test/testcases/dune
- test/testcases/install__distWithBrokenHash.ml
- test/testcases/install__distWithNonHashUnderHashDir.ml
- test/testcases/install__emptyDist.ml
- test/testcases/install__missingDist.ml
- test/testcases/install__onlyDist.ml
- test/testcases/install__thirdParties.ml
- test/testcases/install__thirdParties_brokenDependency.ml
- test/testcases/install__twoDists.ml
- test/testcases/install__unmanagedDirAlreadyExists.ml
- test/testcases/install_l__dependent.ml
- test/testcases/install_l__independentTwo.ml
- test/testcases/install_l__simple.ml
- test/testcases/install_l__thirdParties_brokenDependency.ml
- test/testcases/install_l__transitive.ml
- test/testcases/opam_build__doc_satysfi.ml
- test/testcases/opam_install__doc.ml
- test/testcases/opam_install__library.ml
- test/testcases/opam_install__library_missingHash.ml
- test/testcases/opam_install__library_missingPackage.ml
- test/testcases/opam_install__library_recursive.ml
This is the first step of modularizing Satyrographos implementation.
See https://github.com/na4zagin3/satyrographos/issues/116
> Add satyrograhos_command library

- src/buildScript.ml
- src/library.ml
- src/library.mli
- src/systemFontLibrary.ml
- test/testcases/install__distWithNonHashUnderHashDir.expected
- test/testcases/install__onlyDist.expected
- test/testcases/install__thirdParties.expected
- test/testcases/install_l__dependent.expected
- test/testcases/install_l__independentTwo.expected
- test/testcases/install_l__simple.expected
- test/testcases/install_l__transitive.expected
- test/testcases/opam_install__doc.expected
- test/testcases/opam_install__library.expected
- test/testcases/opam_install__library_recursive.expected
This is to support automatically generated packages.
> Refactoring: Add Library.file type

- src/library.ml
- src/library.mli
- test/testcases/dune
- test/testcases/library_write_dir__content.expected
- test/testcases/library_write_dir__content.ml
This is part of autogen library generation:
V. https://github.com/na4zagin3/satyrographos/issues/112
> Add Content variant to Library.file

- src/autogen/fonts.ml
- src/fontInfo.ml
- src/satysfi.ml
This PR adds more font information to satysfi/experimental/fonts
> Retrieve more font information

- .travis.yml
It'd better to use Bionic rather than Xenial.  This follows up https://github.com/na4zagin3/satyrographos/pull/131
> Update Travis CI dist

- src/command/install.ml
- src/command/opam.ml
- src/command/runSatysfi.ml
- test/testcases/command_opam_build__doc_satysfi.expected
This PR introduces RunSatysfi module, which is to provide a functionality to run SATySFi with specified Satyrographos libraries.
> Add RunSatysfi module

- bin/commandInstall.ml
- bin/commandLibrary.ml
- bin/commandOpam.ml
- bin/commandPin.ml
- bin/commandStatus.ml
- bin/renameOption.ml
Fixes https://github.com/na4zagin3/satyrographos/issues/138
> Remove specifying --help option

- bin/commandSatysfi.ml
Follows up https://github.com/na4zagin3/satyrographos/pull/139 and https://github.com/na4zagin3/satyrographos/pull/137
> Remove standard_help

- bin/dune
- src/command/dune
Cf. https://github.com/na4zagin3/satyrographos-repo/pull/162/files
> Stop ppx_js_style reporting unannotated-ignores

- CHANGELOG.md
- bin/main.ml
- satyrographos.opam
- Updates Changelog
- Bump version
> Bump version to v0.0.2.6

- src/template/templateLib.ml
- test/testcases/command_new__lib.t
- test/testcases/dune
This PR solves #154 except for the LICENSE file.
> Add README.md and .gitignore to the lib template

- .travis.yml
- test/testcases/command_install__distWithNonHashUnderHashDir.expected
- test/testcases/command_install__emptyDist.expected
- test/testcases/command_install__onlyDist.expected
- test/testcases/command_install__thirdParties.expected
- test/testcases/command_install__twoDists.expected
- test/testcases/command_install_l__autogen.expected
- test/testcases/command_install_l__dependent.expected
- test/testcases/command_install_l__independentTwo.expected
- test/testcases/command_install_l__simple.expected
- test/testcases/command_install_l__transitive.expected
- test/testcases/command_new__existing_directory.t
- test/testcases/command_opam_build__doc_satysfi.expected
- test/testcases/command_opam_build__doc_satysfi.ml
- test/testcases/command_opam_install__library.expected
- test/testcases/command_opam_install__library_recursive.expected
- test/testcases/prepareBin.ml
- test/testcases/testLib.ml
This PR have run CI in OSX and Free BSD in addition to Linux, fixing broken unit tests reported in #162.
Closes #162
> Run CI in OSX and Free BSD in addition to Linux

- bin/commandDebug.ml
- src/satysfi/dependencyGraph.ml
- src/satysfi/version.ml
- test/testcases/command_debug_depgraph__satysfi_versions.t
- test/testcases/command_opam_build__doc_satysfi.ml
.satyh-* and .satyg are supported only SATySFi 0.0.4 and later.
> Support SATySFi 0.0.3 package load logic

- bin/commandDebug.ml
- src/satysfi/version.ml
- test/testcases/command_debug_depgraph__empty.t
- test/testcases/command_debug_depgraph__import_duplex.t
- test/testcases/command_debug_depgraph__import_simplex.t
- test/testcases/command_debug_depgraph__missing_files.t
- test/testcases/command_debug_depgraph__require_followed.t
- test/testcases/command_debug_depgraph__require_unfollowed.t
- test/testcases/command_debug_depgraph__subgraph_with_mode.t
Automatically detect SATySFi version from the SATySFi executable in the current path.
> Automatically detect SATySFi version

- bin/commandLint.ml
- src/command/install.ml
- src/command/lint.ml
- src/location.ml
- src/satysfi/dependency.ml
- src/satysfi/dependencyGraph.ml
- src/satysfi/dune
- src/satysfi/mode.ml
- test/testcases/command_debug_depgraph__subgraph_with_mode.t
- test/testcases/command_lint__acyclic_for_each_mode.expected
- test/testcases/command_lint__acyclic_for_each_mode.ml
- test/testcases/command_lint__cyclic_dependencies.expected
- test/testcases/command_lint__cyclic_dependencies.ml
- test/testcases/command_lint__insufficient_dependencies.expected
- test/testcases/command_lint__insufficient_dependencies.ml
- test/testcases/command_lint__insufficient_dependencies_for_some_modes.expected
- test/testcases/command_lint__insufficient_dependencies_for_some_modes.ml
- test/testcases/command_lint__missing_file.expected
- test/testcases/command_lint__missing_file.ml
- test/testcases/command_lint__packages_for_different_modes.expected
- test/testcases/command_lint__packages_for_different_modes.ml
- test/testcases/dune
- test/testlib/testCommand.ml
This PR adds linters of the following problems:
- A package require/import another package, which is missing.
- Cyclic dependency of packages.
Closes https://github.com/na4zagin3/satyrographos/issues/148
> Lint: Detect dependency problems

- src/template/templateLib.ml
- test/testcases/command_new__lib.t
- Add dependencies
- Add example URLs for a GitHub-hosted project
> Resolve lint errors in the lib template

- src/autogen/today.ml
- src/command/install.ml
- test/testcases/command_install_l__autogen.ml
This commit adds %today package which has the current datatime.
> Add %today autogen package

- README-ja.md
- README.md
- doc/logo.svg
I just created a simple logo, combining Linear B _sa_ and _tu_.
> Add logo.svg

- src/template/template.ml
- src/template/templateDocMakeEn.ml
- src/template/templateDocMakeJa.ml
- test/testcases/command_new__doc_make.t
This PR adds a new document template in Japanese.
> Add doc-make@ja template

- src/buildScript_0_0_2.ml
- src/buildScript_0_0_3.ml
- src/buildScript_prim.ml
This refactors BuildScript.read_module with polymorphic variant for documentSource
> Refactor BuildScript.read_module

- src/library.ml
- test/testcases/command_opam_install__duplicated_font_hash.expected
- test/testcases/command_opam_install__font_hash.expected
- test/testcases/command_opam_install__font_hash.ml
> Fix a bug which prevents using multiple font sources

- src/autogen/fonts.ml
- src/autogen/fontsSystem.ml
- src/autogen/libraries.ml
- src/autogen/today.ml
- test/testcases/command_build__doc_with_autogen.expected
- test/testcases/command_build__doc_with_autogen.ml
- test/testcases/command_install_l__autogen.expected
- test/testcases/command_install_l__autogen.ml
- test/testcases/command_install_l__invalid_autogen.expected
- test/testcases/command_install_l__invalid_autogen.ml
- test/testcases/command_lint__autogen.ml
- test/testcases/command_lockdown_restore__opam.ml
- test/testcases/command_opam_install__library_depending_autogen.expected
- test/testcases/command_opam_install__library_depending_autogen.ml
- test/testlib/prepareOpamReg.ml
> Rename autogen libraries

- src/command/lint_module_dependency.ml
- test/testcases/command_lint__valid_reference_to_parent_dir.expected
- test/testcases/command_lint__valid_reference_to_parent_dir.ml
- test/testcases/dune
This PR fixes this problem:
https://github.com/na4zagin3/satyrographos-repo/pull/216#issuecomment-723507798
> Allow parent references in require/import directives

- README-ja.md
- README.md
- src/buildScript_0_0_2.ml
- src/buildScript_0_0_3.ml
- src/buildScript_prim.ml
- test/testcases/command_new__example_autogen.t
- test/testcases/command_opam_install__library.expected
- test/testcases/command_opam_install__library.ml
I have added "md" module.
ex.
```
(sources
((md "mdja.satysfi-md" "src/md/mdja.satysfi-md")))
```
> Add "md" source

- src/template/template_docMake_en.ml
- src/template/template_docMake_ja.ml
- src/template/template_docOmake_en.ml
- src/template/template_docOmake_ja.ml
- src/template/template_exampleAutogen.ml
- src/template/template_fonts.ml
- src/template/template_lib.ml
As I'd like to allow the users to choose from as many licenses as possible, I apply CC0 which is virtually equivalent to public domain.
> Apply CC0-1.0 license to templates

- bin/commandOpam.ml
- src/command/opam.ml
- src/satysfi/migration.ml
- src/satysfi/version.ml
- test/testcases/command_opam_install__library.expected
- test/testcases/command_opam_install__library_recursive.expected
Also when Satyrographos cannot recognize SATySFi version, it assumes the latest version that the Satyrographos knows.
Close https://github.com/na4zagin3/satyrographos/issues/80
Close https://github.com/na4zagin3/satyrographos/issues/10
> Automatically convert src-dist field into src field

- src/command/new.ml
- test/testcases/command_new__lib.t
Update the SATySFi version of lib template.
> update satysfi version

- src/command/install.ml
- src/library.ml
- src/library.mli
This addresses problem https://github.com/na4zagin3/satyrographos/issues/287
Close https://github.com/na4zagin3/satyrographos/issues/287
> Don't stop when non-dependent libraries are removed

- .github/workflows/ci.yaml
> Use setup-ocaml v2

- satyrographos.opam
- src/lockdown/dune
- src/lockdown/lockdownFile.ml
- src/lockdown/yamlYojson.ml
This commit updates the depended version of yaml from 2.x to 3.x.
> Update yaml library to 3.0
