na4zagin3/satyrographos

- bin/main.ml
- satyrographos.opam
- src/dune
- src/package.ml
- src/registory.ml
- src/repository.ml
- src/systemFontPackage.ml
This PR makes it possible to
- install system fonts with command line option `-system-font-prefix <system-font-name-prefix>`, and
- control verbosity of messages with command line option `-verbose`.
This only works on Mac and Linux Desktop Environments because it assumes the system has `fc-list` in PATH, which means [fontconfig](https://www.freedesktop.org/wiki/Software/fontconfig/) has been installed there. This should work on Cygwin as well, while I have no idea about Windows Subsystem of Linux (WSL).
Currently, it does not handle fonts with the same filename. I will work on that later.
Resolves #2.
> Install system fonts

- bin/main.ml
- src/satysfiDirs.ml
This bug was introduced by #11 .
This correctly implements #9
> Fix bug where packages installed in opam are ignored

- bin/main.ml
Since v0.0.1.2 Satyrographos makes symlinks instead of copying files to reduce replicated files. Apparently copying is required in some cases. This PR exposes the copying functionality with CLI `install -copy`.
https://github.com/amutake/satysfi-docker/issues/1
> Expose copying install option as `install -copy` (in contrast with symlinks)

- bin/main.ml
- satyrographos.opam
- src/package.ml
Unfortunately, breaking changes introduced in v0.12 actually do break Satyrographos.
- The type of `Unix.symlink` has been changed.
- Command.Param.file has been removed.
This PR fixes them and make it compatible with the both versions.
> Core v0.12 support

- bin/main.ml
- src/package.ml
- src/satysfiDirs.ml
This PR introduces the following changes.
- When the environment lacks an OPAM executable, `package-opam` commands does not anything, and `install` uses `/usr/local/share/satysfi/dist` or `/usr/share/satysfi/dist` as  .
- Even when a package, including the satysfi dist source, contains file `/.satyrographos`, it is simply ignored not to cause any error.
Addresses #20
> Support opam-free environment

- satyrographos.opam
- src/dune
Url library has been divided into url and url-sexp.
> Bump url library version to 3 series

- bin/commandInstall.ml
- bin/setup.ml
Add `-package PACKAGE` option to `install` subcommand.
Without any `-package` options, it installs all the package to keep backward compatibility.
Specifying `dist` package is no-op, therefore can skip installing third-party libraries.
> Add -package option

- bin/commandInstall.ml
- bin/commandOpam.ml
- bin/dune
- bin/main.ml
- bin/setup.ml
- satyrographos.opam
- src/buildScript.ml
- src/dune
- src/package.ml
- src/systemFontPackage.ml
Now Satyrographos reads a build file, typically named `Satyristes`, to install/uninstall files into OPAM prefix. This functionarity is to replace Makefile.
Note: `satyrographos install` does not yet respect dependencies!
> Support build script

- bin/commandInstall.ml
- bin/commandOpam.ml
- src/buildScript.ml
- src/library.ml
- src/systemFontLibrary.ml
Add field `compatibility` and `satyrographos-0.0.1` tag to Satyristes.
```
(library
(name "grcnum")
(sources
((package "grcnum.satyh" "./grcnum.satyh")))
(opam "satysfi-grcnum.opam")
(dependencies ((fonts-theano ())))
(compatibility (satyrographos-0.0.1)))
```
The tag will have `satyrographos install` output compatibility notices.
```
$ satyrographos install -library grcnum
...
Installation completed!
Compatibility notice for library grcnum:
Packages have been renamed.
package grcnum.satyh -> package grcnum/grcnum.satyh.
```
Closes #37
> Implement compatibility warnings

- bin/commandOpam.ml
- bin/dune
- satyrographos.opam
- src/buildScript.ml
Added a new section `LibraryDoc` to Satyristes.
```lisp
;;; Satyristes 
(version 1)
(library
(name "fonts-theano")
(sources
((hash "fonts.satysfi-hash" "./fonts.satysfi-hash")
(font "TheanoDidot-Regular.otf" "./theano/TheanoDidot-Regular.otf")
(font "TheanoModern-Regular.otf" "./theano/TheanoModern-Regular.otf")
(font "TheanoOldStyle-Regular.otf" "./theano/TheanoOldStyle-Regular.otf")))
(opam "satysfi-fonts-theano.opam"))
(libraryDoc
(name "fonts-theano-doc")
(build
((satysfi "doc-fonts-theano-ja.saty" "-o" "doc-fonts-theano-ja.pdf" )))
(sources
((doc "doc-fonts-theano-ja.pdf" "./doc-fonts-theano-ja.pdf")))
(opam "satysfi-fonts-theano-doc.opam")
(dependencies ((fonts-theano ()))))
```
```sh
$ satyrographos opam build -name fonts-theano-doc -verbose
```
```lisp
;;; Satyristes for …
```
> Build Librady Doc

- bin/commandInstall.ml
- src/buildScript.ml
- src/library.ml
Changed compatibility field so that it can convey arbitrary compatibility notices.
Examples:
```lisp
(version 1)
(library
(name "fonts-theano")
(sources
((hash "fonts.satysfi-hash" "./fonts.satysfi-hash")
(font "TheanoDidot-Regular.otf" "./theano/TheanoDidot-Regular.otf")
(font "TheanoModern-Regular.otf" "./theano/TheanoModern-Regular.otf")
(font "TheanoOldStyle-Regular.otf" "./theano/TheanoOldStyle-Regular.otf")))
;;; Here
(compatibility ((renameFont fonts-theano:TheanoDidot TheanoDidot)
(renameFont fonts-theano:TheanoModern TheanoModern)
(renameFont fonts-TheanoOldStyle TheanoOldStyle)))
(opam "satysfi-fonts-theano.opam"))
(libraryDoc
(name "fonts-theano-doc")
(build
((satysfi "doc-fonts-theano-ja.saty" "-o" "doc-fonts-theano-ja.pdf")))
(sources
((doc "doc-fonts-theano-ja.pdf" …
```
> Add font/package compatibility notices

- src/systemFontLibrary.ml
#72 に対する修正案です。
（手元の環境 macOS Mojave 10.14.6 で動作確認を行いました。）
> Fix filepath in fonts.satysfi-hash

- bin/commandInstall.ml
Now `satyrographos install -l lib1 -l lib2` means `satyrographos install -library lib1 -library lib2`.
Closes #68
> Add -l as an alias of -library option of install subcommand

- bin/commandInstall.ml
- bin/commandOpam.ml
- bin/commandPin.ml
- bin/commandStatus.ml
- bin/setup.ml
- src/commandInstall.ml
- src/commandOpam.ml
- src/library.ml
- src/registry.ml
- src/repository.ml
- src/satysfiDirs.ml
- src/systemFontLibrary.ml
Use `Format.fprintf` everywhere instead of `Format.printf` or `Printf.printf`.
> Refactoring: Output every lines to the given formatter

- bin/commandOpam.ml
- bin/commandStatus.ml
- bin/setup.ml
- src/Environment.ml
- src/commandInstall.ml
- src/commandOpam.ml
- src/satysfiDirs.ml
Add dist_runtime_dir to Environment.t in order to reduce implicit environmental dependencies.
This is part of #19.
> Refactoring: Explicitly handle dist runtime directory

- src/library.ml
This PR can introduce incompatibility for users who are using OCaml 4.09 and having opted-in `pin` subcommand use. I believe number of affected people is negligibly small.
Closes https://github.com/na4zagin3/satyrographos/issues/88
> Stop using [@sexp.option] which is not supported by older ppx_sexp_conv

- satyrographos.opam
- test/testcases/dune
- test/testcases/install__emptyDist.expected
- test/testcases/install__emptyDist.ml
- test/testcases/install__missingDist.expected
- test/testcases/install__missingDist.ml
- test/testcases/install__onlyDist.expected
- test/testcases/install__onlyDist.ml
- test/testcases/install__thirdParties.expected
- test/testcases/install__thirdParties.ml
- test/testcases/install__unmanagedDirAlreadyExists.expected
- test/testcases/install__unmanagedDirAlreadyExists.ml
- test/testcases/prepareDist.ml
- test/testcases/prepareOpamReg.ml
- test/testcases/testLib.ml
- test/testcases/testLib.mli
This PR introduce a simple snapshot tests for install subcommand in simple situations, where there are no thirdparty libraries or system fonts.
This is part of #19 .
> Snapshot tests for install subcommand

- src/commandOpam.ml
- src/processUtil.ml
- src/processUtil.mli
- test/testcases/opam_build__doc_satysfi.expected
This PR adds prefix to each line of output from external commands (i.e., make and satysfi) like this:
```
satysfi err>
satysfi err> Command invoked:
satysfi err> satysfi -C @@build_temp_dir@@ doc-grcnum.saty -o doc-grcnum-ja.pdf
satysfi out> INPUT=doc-grcnum.saty
satysfi out> OUTPUT=doc-grcnum-ja.pdf
satysfi err> doc-grcnum.saty -> doc-grcnum-ja.pdf
satysfi err>
make out> Target: build-doc
make out> Files under $SATYSFI_RUNTIME
make out> ==============================
make out> .:
```
> Add redirection prefix for external command execution

- src/processUtil.ml
- test/testcases/opam_build__doc_satysfi.expected
- test/testcases/prepareBin.ml
For more stable snapshot testing, stop redirection from stderr to stdout.
This will be finally resolved by #42 .
> Output invoked command to stdout

- test/testcases/opam_build__doc_satysfi.expected
- test/testcases/opam_build__doc_satysfi.ml
- test/testcases/prepareBin.ml
- test/testcases/testLib.ml
- test/testcases/testLib.mli
To get stable snapshot, leave external command invocations in a file rather than stdout.
> Log command invocation to a file rather than stdout

- src/library.ml
- test/testcases/dune
- test/testcases/install__distWithBrokenHash.expected
- test/testcases/install__distWithBrokenHash.ml
- test/testcases/testLib.ml
- test/testcases/testLib.mli
#110 also has a problem where JSON format error does not have filenames. This PR adds a filename to a JSON format error.
> Show filename when JSON parser raises an exception

- src/command/install.ml
- src/libraryMap.ml
Move utility functions in `Satyrographos_command.Install` into `Satyrographos.LibraryMap`.
> Refactoring: Add LibraryMap module

- bin/commandInstall.ml
- src/autogen/dune
- src/autogen/fonts.ml
- src/autogen/libraries.ml
- src/command/dune
- src/command/install.ml
- src/satysfi.ml
- test/testcases/command_install_l__autogen.expected
- test/testcases/command_install_l__autogen.ml
- test/testcases/dune
Satysfi_autogen library has two autogen libraries:
- `satyrographos/experimental/fonts`: list of installed fonts
- `satyrographos/experimental/libraries`: list of installed libraries
Those libraries will be used with `-a` option of `install` subcommand like:
satyrographos install -a '%libraries' -a '%fonts'
This PR makes it possible to write a font specimen document like https://gist.github.com/na4zagin3/4c9d32cb9659e128cdd35e3f650539bc
This is an initial step of https://github.com/na4zagin3/satyrographos/issues/112
> Add Satysfi_autogen library

- src/command/install.ml
- src/systemFontLibrary.ml
- test/testcases/command_install__distWithNonHashUnderHashDir.expected
- test/testcases/command_install__emptyDist.expected
- test/testcases/command_install__onlyDist.expected
- test/testcases/command_install__thirdParties.expected
- test/testcases/command_install__twoDists.expected
- test/testcases/command_install_l__autogen.expected
- test/testcases/command_install_l__dependent.expected
- test/testcases/command_install_l__independentTwo.expected
- test/testcases/command_install_l__simple.expected
- test/testcases/command_install_l__transitive.expected
As #122 expose names and versions of autogen libraries, it’d better to assign proper values to them.
Version field of `dist` library will be addressed with #123.
Related to #112
> Set proper values to autogen libraries’ information fields

- bin/commandOpam.ml
This PR deprecates `opam uninstall` subcommand which should not do anything as OPAM removes Satyristes file before the command was invoked.
> Deprecate opam uninstall subcommand

- .travis.yml
- Remove `sudo: required` to suppress a warning
- It's now deprecated: https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments
- Add Linux distribution: `xenial` (Ubuntu 16.04)
- Would it be better `bionic` (Ubuntu 18.04) than `xenial`?
- For now I deal with to remove the unspecified warning at first
- Add cache setting, which is the same as https://github.com/gfngfn/SATySFi/pull/227
> Fix Travis CI setting and add cache setting

- bin/commandInstall.ml
- bin/commandLibrary.ml
- bin/commandOpam.ml
- bin/commandPin.ml
- bin/commandStatus.ml
- bin/dune
- bin/renameOption.ml
- src/command/runSatysfi.ml
- src/systemFontLibrary.ml
This PR adds GNU Style long options (e.g., `--library`) and deprecates those that does not follow the rule (e.g., `-library`).
Additionally, this PR adds `--use-system-fonts` option to `install` subcommand, fixing system font prefix to `system:`.
> Add GNU style long options and deprecate old ones

- bin/renameOption.ml
This commit fixes a bug where option deprecation warnings are shown
regardless of whether they are.
This follows up https://github.com/na4zagin3/satyrographos/pull/134.
> Fix a bug of option deprecation warnings

- bin/commandSatysfi.ml
- bin/dune
- bin/main.ml
This PR adds `satysfi`subcommand, which takes options for install subcommand as well as
`--` followed by arguments for SATySFi.
> Add satysfi subcommand

- bin/commandInstall.ml
This retract `--use-system-fonts` option introduced with https://github.com/na4zagin3/satyrographos/pull/134
> Revert deprecation of --system-font-prefix option

- README-ja.md
- README.md
Now long option names should start with two hyphens, for example `--name`.
> Update long option names

- bin/commandNew.ml
- bin/dune
- bin/main.ml
- dune-project
- src/command/dune
- src/command/new.ml
- src/template/dune
- src/template/template.ml
- src/template/templateLib.ml
- test/testcases/command_new__existing_directory.t
- test/testcases/command_new__invalid_license_option.t
- test/testcases/command_new__lib.t
This PR adds a new subcommand `new` for creating document/library from the chosen template.  This is a part of #153.
As the first step, this PR also includes a template `lib` for a new library.
Usage:
```
$ SATYROGRAPHOS_EXPERIMENTAL=1 satyrographos new lib test-lib
Compatibility warning: You have opted in to use experimental features.
Name: test-lib
Choose licenses:
0) MIT
1) LGPL-3.0-or-later
> 1
License: LGPL-3.0-or-later
Created a new library/document.
```
> Add new subcommand for creating a document/library from a template

- src/command/new.ml
- test/testcases/command_new__invalid_names.t
Project names should consist only of ASCII alphabets, numbers, underscores, and hyphens.
Closes #155.
> Reject invalid project names for new projects

- .travis.yml
- src/command/install.ml
- test/testcases/command_install__distWithNonHashUnderHashDir.expected
- test/testcases/command_install__emptyDist.expected
- test/testcases/command_install__onlyDist.expected
- test/testcases/command_install__thirdParties.expected
- test/testcases/command_install__twoDists.expected
- test/testcases/command_install_l__autogen.expected
- test/testcases/command_install_l__dependent.expected
- test/testcases/command_install_l__independentTwo.expected
- test/testcases/command_install_l__simple.expected
- test/testcases/command_install_l__transitive.expected
- test/testcases/command_new__existing_directory.t
- test/testcases/command_opam_build__doc_satysfi.expected
- test/testcases/command_opam_build__doc_satysfi.ml
- test/testcases/command_opam_install__library.expected
- test/testcases/command_opam_install__library_recursive.expected
- test/testcases/library_write_dir__content.expected
- test/testcases/prepareBin.ml
- test/testcases/testLib.ml
This PR fixes #86 like below message:
```
Installation completed!
Compatibility notice for library assert-eq:
Packages have been renamed.
assert-eq.satyg -> assert-eq/assert-eq.satyg
Compatibility notice for library class-exdesign:
Packages have been renamed.
article-ja.satyh -> class-exdesign/article-ja.satyh
exdesign.satyh -> class-exdesign/exdesign.satyh
Compatibility notice for library class-slydifi:
Packages have been renamed.
functions/color.satyh -> class-slydifi/functions/color.satyh
functions/figbox.satyh -> class-slydifi/functions/figbox.satyh
functions/footnote.satyh -> class-slydifi/functions/footnote.satyh
functions/overlay.satyh -> class-slydifi/functions/overlay.satyh
functions/param.satyh -> class-slydifi/functions/param.satyh
slydifi.satyh -> class-slydifi/slydifi.satyh …
```
> Fix indents in compatibility warning messages

- bin/commandLint.ml
- bin/dune
- bin/main.ml
- satyrographos.opam
- src/buildScript.ml
- src/command/dune
- src/command/lint.ml
- test/testcases/command_lint__invalid_opam_file.expected
- test/testcases/command_lint__invalid_opam_file.ml
- test/testcases/command_lint__missing_dependencies.expected
- test/testcases/command_lint__missing_dependencies.ml
- test/testcases/command_lint__missing_opam.expected
- test/testcases/command_lint__missing_opam.ml
- test/testcases/command_lint__missing_satyristes.expected
- test/testcases/command_lint__missing_satyristes.ml
- test/testcases/command_lint__unmatched_names.expected
- test/testcases/command_lint__unmatched_names.ml
- test/testcases/command_lint__unmatched_versions.expected
- test/testcases/command_lint__unmatched_versions.ml
- test/testcases/command_lint__valid.expected
- test/testcases/command_lint__valid.ml
- test/testcases/command_lint__valid_in_specified_location.expected
- test/testcases/command_lint__valid_in_specified_location.ml
- test/testcases/command_lint__valid_versions.expected
- test/testcases/command_lint__valid_versions.ml
- test/testcases/dune
- test/testcases/prepareOpamReg.ml
- test/testcases/testCommand.ml
- test/testcases/testLib.ml
- test/testcases/testLib.mli
This PR adds `lint` subcommand to check validity of Satyristes and OPAM files.
The command checks...
- if OPAM package names follow Satyristes naming convention;
- if each OPAM package version prefixed with Satyristes module version (e.g., if Satyristes module version is `0.1`, OPAM package versions should be for example `0.1+1`, `0.1a`, `0.1.1` but not `0.11`, `1` etc.);
- if each OPAM package has OPAM package dependencies corresponding to dependencies described in Satyristes; and
- if each OPAM file has no errors
Closes https://github.com/na4zagin3/satyrographos/issues/150
> Add lint subcommand

- bin/commandInstall.ml
- bin/renameOption.ml
Especially SATYSFI_ROOT is too confusing because SATYSFI_ROOT environment
variable is used to specify something like ~/.satysfi rather than ~/.satysfi/dist.
> Fix typo SATYSFI_ROOT

- doc/terminology.md
This file is to use unified terms throughout the Satyrographos codebase.
> Add terminology.md

- bin/commandDebug.ml
- bin/dune
- bin/main.ml
- satyrographos.opam
- src/satysfi/dependency.ml
- src/satysfi/dependencyGraph.ml
- src/satysfi/dune
- src/satysfi/mode.ml
- src/satysfi/satysfiDirs.ml
- src/satysfi/version.ml
- test/testcases/command_debug_depgraph__empty.t
- test/testcases/command_debug_depgraph__import_duplex.t
- test/testcases/command_debug_depgraph__import_simplex.t
- test/testcases/command_debug_depgraph__missing_files.t
- test/testcases/command_debug_depgraph__require_followed.t
- test/testcases/command_debug_depgraph__require_unfollowed.t
This PR adds module DependencyGraph to a construct dependency graph of SATySFi source files.
This PR also adds `debug depgraph` subcommand to output the dependency graph as a DOT file.
Example ([satysfi-fss](https://github.com/na4zagin3/satysfi-fss)):
> Add DependencyGraph module

- bin/commandLibrary.ml
- bin/commandPin.ml
- bin/commandStatus.ml
- bin/setup.ml
- bin/setup.mli
- src/command/install.ml
- src/command/pin.ml
- src/command/pin.mli
- src/environment.ml
- src/environment.mli
- src/satyrographosDirs.ml
- test/testcases/command_install__unmanagedDirAlreadyExists.ml
- test/testlib/testLib.ml
Satyrographos Depot and Satyrographos Registry were confusingly called Repo and Library.  This PR replaces the old usages with the new tems.
> Refactoring: Use unified terminology: depot and registry

- src/buildScript_0_0_2.ml
- src/buildScript_prim.ml
This PR does microrefactoring of BuildScript related types.
Unfortunately, I didn't come up with a clear structure of `BuildScript_prim.m`.  That will be addressed in another PR.
> Microrefactoring of BuildScript related types

- bin/commandDebug.ml
- src/satysfi/dependency.ml
- src/satysfi/dependencyGraph.ml
- test/testcases/command_debug_depgraph__missing_files.t
- test/testcases/command_debug_depgraph__subgraph_with_mode.t
This PR improves DependencyGraph with
- Adding functions to get a subgraph with specific typesettinng `mode` (e.g., `.satyh`, `.satyh-md`, `.satyg`)
- Having missing files reported in the graph
> Improve DependencyGraph

- src/environment.ml
- src/environment.mli
- test/testcases/command_lint__missing_dependencies.ml
- test/testcases/command_lint__unmatched_names.ml
- test/testcases/command_lint__unmatched_versions.ml
- test/testcases/command_lint__valid.ml
- test/testcases/command_lint__valid_in_specified_location.ml
- test/testlib/testCommand.ml
This PR has lint test cases prepare libraries in the OPAM registry.
> Prepare dependent libraries for each test cases for lint subcommand 

- bin/main.ml
- satyrographos.opam
This PR have `dune subst` substitute version placeholder `%%VERSION_NUM%%` for `opam pin` with a workaround.
Unfortunately `dune exec -- satyrographos --version` does not show a correct version.  This problem will be addresses by a following ticket.
Cf. https://github.com/gfngfn/SATySFi/pull/167
> Let Dune update version number in the command help

- src/satysfi/version.ml
This PR adds support of new version schema added by <https://github.com/gfngfn/SATySFi/pull/167>.
> Support SATySFi versions with commit suffix

- bin/commandBuild.ml
- bin/commandDebug.ml
- bin/commandSatysfi.ml
- bin/dune
- bin/main.ml
- src/buildScript_0_0_2.ml
- src/buildScript_prim.ml
- src/command/build.ml
- src/command/opam.ml
- src/command/runSatysfi.ml
- src/environment.ml
- src/environment.mli
- test/testcases/command_build__doc_make.expected
- test/testcases/command_build__doc_make.ml
- test/testcases/command_build__doc_satysfi.expected
- test/testcases/command_build__doc_satysfi.ml
- test/testcases/command_build__doc_with_libraries.expected
- test/testcases/command_build__doc_with_libraries.ml
- test/testcases/command_opam_build__doc_satysfi.expected
- test/testcases/command_satysfi__with_project_env.expected
- test/testcases/command_satysfi__with_project_env.ml
- test/testcases/dune
- test/testlib/prepareBin.ml
- test/testlib/testLib.ml
- test/testlib/testLib.mli
This PR adds `build <module-name>` subcommand which does
- Run `opam pin add --yes <opam-package>name; "file://<package-directory>"` for each library or libraryDoc module in the Satyristes
- If the module `<module-name>` has `build` section, Satyrographos executes it.
On the same time behaviors of some existing features are also changed.
- When Satyrographos executes a `make` clause in `build` sections, it runs make command with `SATYROGRAPHOS_PROJECT` environment variable, which has a path to SATySFi Root Directory.
- When `SATYROGRAPHOS_PROJECT` environment variable exists, `satysfi` subcommand read packages from SATySFi Root Directory specified by the environment variable rather than creating one in the temp directory.
- New module type `doc` is added to Satyristes.
> Add build subcommand

- test/testcases/dune
- test/testlib/prepareBin.ml
- test/testlib/testCommand.ml
- test/testlib/testLib.ml
This PR has PATH updated in Shexp_process as well as OCaml putenv and has the test cases depend on satyrographos executable.
Resolves #199.
> Update PATH in the Shexp_process.t

- bin/commandDebug.ml
- bin/commandUtil.ml
- bin/dune
- bin/main.ml
- src/satysfi/dependencyGraph.ml
- src/satysfi/mode.ml
- test/testcases/command_build__doc_make.expected
- test/testcases/command_build__doc_make.ml
- test/testcases/command_debug_depgraph__empty.t
- test/testcases/command_debug_depgraph__import_duplex.t
- test/testcases/command_debug_depgraph__import_simplex.t
- test/testcases/command_debug_depgraph__missing_files.t
- test/testcases/command_debug_depgraph__require_followed.t
- test/testcases/command_debug_depgraph__require_unfollowed.t
- test/testcases/dune
This PR adds `util deps-make` subcommand, which produces dependency files for Make.
> Add "util deps-make" subcommand

- src/buildScript.ml
- src/buildScript_0_0_3.ml
- src/buildScript_prim.ml
- src/command/build.ml
- src/command/lint.ml
- src/command/opam.ml
- test/testcases/command_build__doc_make.ml
- test/testcases/command_build__doc_satysfi.ml
- test/testcases/command_build__doc_with_libraries.ml
This script simply adds Build Script lang version 0.0.3, copying version 0.0.2, and remove `doc` module support from version 0.0.2.
> Add Script lang 0.0.3

- bin/commandUtil.ml
- test/testcases/command_debug_depgraph__empty.t
- test/testcases/command_debug_depgraph__import_duplex.t
- test/testcases/command_debug_depgraph__import_simplex.t
- test/testcases/command_debug_depgraph__missing_files.t
- test/testcases/command_debug_depgraph__require_followed.t
- test/testcases/command_debug_depgraph__require_unfollowed.t
- test/testcases/command_util_deps_make__output_stdout.t
- test/testcases/command_util_deps_make__phony_targets.t
- adds alias `-f` to `--depfile` option
- adds `--phony-target` option to toggle adding phony targets
- replaces `--output-extension` (alias `-e`) option with `--target` (alias `-o`)
to specify a whole filename instead of an extension
This PR follows up https://github.com/na4zagin3/satyrographos/pull/197
> Improve commandline options of util deps-make subcommand

- bin/commandDebug.ml
- bin/commandUtil.ml
- src/satysfi/mode.ml
- test/testcases/command_debug_depgraph__subgraph_with_mode.t
Instead of extensions (e.g., `.satyh`, `.satyh-md`, `.satyg`), use more
intuitive names (e.g., `pdf`, `text-md`, `generic`).
> Use more intuitive mode names in commandline options

- src/template/template.ml
- src/template/templateDocMake.ml
- test/testcases/command_new__doc_make.t
This PR adds new template `doc-make` for a document project.
> Add doc-make template

- src/buildScript_prim.ml
- src/command/lint.ml
- test/testcases/command_lint__compatibility_satyrographos_0_0_1.expected
- test/testcases/command_lint__compatibility_satyrographos_0_0_1.ml
- test/testcases/command_opam_install__library.expected
- test/testcases/command_opam_install__library_recursive.expected
- test/testcases/dune
This PR removes compatibility notices for Satyrographos 0.0.1 libraries, with adding a lint rule for that.
> Remove compatibility notices for Satyrographos 0.0.1 libraries

- src/command/build.ml
- src/command/runSatysfi.ml
- test/testcases/command_build__doc_make.expected
- test/testcases/command_build__doc_satysfi.expected
- test/testcases/command_build__doc_with_libraries.expected
- test/testcases/command_opam_build__doc_satysfi.expected
This PR removes prefixes (e.g., `make out>`) that were attached to make/satysfi command output lines.
> Don't add a prefix to each line of command outputs

- bin/commandMigrate.ml
- bin/dune
- bin/main.ml
- src/buildScript.ml
- src/buildScript_0_0_2.ml
- src/buildScript_0_0_3.ml
- src/buildScript_prim.ml
- src/command/build.ml
- src/command/migrate.ml
- test/testcases/command_migrate__build_0_0_2.t
This PR adds `migrate` subcommand, which converts a Satyrographos 0.0.2 project for a Satyrographos 0.0.3 project.
> Add migrate subcommand

- src/buildScript.ml
- src/buildScript_0_0_3.ml
- src/buildScript_prim.ml
- src/command/build.ml
- src/command/lint.ml
- src/command/lint_problem.ml
- src/command/migrate.ml
- src/template/templateDocMakeEn.ml
This PR adds (run ...) build command to LibraryDoc and Doc modules.
A new warning `lib/build/deprecated/make` is also added. That will warn when `(make ...)` is used in build script language 0.0.3.
This is a part of https://github.com/na4zagin3/satyrographos/issues/168
> Add (run ...) build command to LibraryDoc and Doc modules

- .travis.yml
As OPAM rebuilds everything for each time in Travis, we can only cache the downloaded files.
> Cache only downloaded files

- src/satysfi/version.ml
This PR has get_current_version return None when SATySFi is not installed.  Otherwise, `satysfi lint` command fails with an improper message when SATySFi is not installed.
> Have get_current_version return None when SATySFi is not installed

- src/template/template.ml
- src/template/template_docOmake_en.ml
- src/template/template_docOmake_ja.ml
- test/testcases/command_new__doc_omake.t
This PR adds document templates `doc-omake@en` and `doc-omake@ja` using OMake for build management.
> Add doc-omake@en and doc-omake@ja templates

- bin/commandLockdown.ml
- bin/dune
- bin/main.ml
- satyrographos.opam
- src/buildScript_prim.ml
- src/command/dune
- src/command/lockdown.ml
- src/lockdown/dune
- src/lockdown/lockdown.ml
- src/lockdown/lockdownFile.ml
- src/lockdown/opamDependencies.ml
- src/lockdown/yamlYojson.ml
- test/testcases/command_lockdown_restore__opam.expected
- test/testcases/command_lockdown_restore__opam.ml
- test/testcases/command_lockdown_save__invalid_opam_response.expected
- test/testcases/command_lockdown_save__invalid_opam_response.ml
- test/testcases/command_lockdown_save__opam.expected
- test/testcases/command_lockdown_save__opam.ml
- test/testcases/dune
- test/testlib/prepareBin.ml
- test/testlib/testLib.ml
- test/testlib/testLib.mli
This PR adds lockdown subcommand which save all the transiently dependent
OPAM packages into lockdown.yaml and also restore them from the lockdown file.
This is the first step of https://github.com/na4zagin3/satyrographos/issues/98
> Add lockdown subcommand to save/restore OPAM package dependencies

- src/buildScript_0_0_2.ml
- src/buildScript_0_0_3.ml
- src/buildScript_prim.ml
- src/command/build.ml
- src/command/lint.ml
- src/command/lint_problem.ml
- src/template/template_docMake_en.ml
- src/template/template_docMake_ja.ml
- src/template/template_docOmake_en.ml
- src/template/template_docOmake_ja.ml
- test/testcases/command_build__doc_make.expected
- test/testcases/command_build__doc_make.ml
- test/testcases/command_build__doc_satysfi.expected
- test/testcases/command_build__doc_satysfi.ml
- test/testcases/command_build__doc_with_libraries.expected
- test/testcases/command_build__doc_with_libraries.ml
This PR changes build rules in script lang 0.0.3.
- adds `(omake ...)` build rule
- adds `(make-with-env-var ...)` build rule which behaves as same as `(make ...)` in script lang 0.0.2
- keeps `(make ...)` from setting `$SATYSFI_RUNTIME`
> Add (omake ...) build rule

- README-ja.md
- README.md
- bin/commandNew.ml
- doc/internals.ja.md
- doc/internals.md
- src/template/template_docMake_en.ml
- src/template/template_docMake_ja.ml
- src/template/template_docOmake_en.ml
- src/template/template_docOmake_ja.ml
- test/testcases/command_new__doc_make.t
- test/testcases/command_new__doc_omake.t
- test/testcases/command_new__existing_directory.t
- test/testcases/command_new__invalid_license_option.t
- test/testcases/command_new__invalid_names.t
- test/testcases/command_new__lib.t
This PR removes the opt-in gate for `new` subcommand.
At the same time, templates with experimental features are marked with `[experimental]` prefix in their template names.
Resolves https://github.com/na4zagin3/satyrographos/issues/153
> Stabilize new subcommand

- README-ja.md
- README.md
- bin/commandLint.ml
- doc/lint.md
- test/testcases/command_new__doc_make.t
- test/testcases/command_new__doc_omake.t
- test/testcases/command_new__lib.t
This PR removes the opt-in gate for lint subcommand.
> Stabilize `lint` subcommand

- src/autogen/fonts.ml
- src/autogen/libraries.ml
- src/autogen/today.ml
- src/satysfi/writer.ml
- src/template/template.ml
- src/template/template_exampleAutogen.ml
- test/testcases/command_build__doc_with_autogen.expected
- test/testcases/command_build__doc_with_autogen.ml
- test/testcases/command_install_l__autogen.expected
- test/testcases/command_install_l__autogen.ml
- test/testcases/command_lint__autogen.ml
- test/testcases/command_new__example_autogen.t
- test/testlib/prepareOpamReg.ml
Example:
```
$ satyrographos new [experimental]example-autogen --license CC-BY-4.0 test-example-autogen
```
This PR also fixes the module name and the field names of `$today` autogen library.  Also changed import paths of other autogen libraries.
> Add a template with autogen libraries

- src/satysfi/dependencyGraph.ml
- src/satysfi/mode.ml
- test/testcases/command_debug_depgraph__subgraph_with_mode.t
- test/testcases/command_lint__insufficient_dependencies_for_some_modes.ml
This fixes a bug where `lint` reports non-problematic imports as in https://github.com/na4zagin3/satyrographos-repo/pull/216#issuecomment-723535012
> Make subgraph_with_mode remove vertices as well as edges

- src/satysfi/dependency.ml
- src/satysfi/dependencyGraph.ml
- test/testcases/command_debug_depgraph__satysfi_md.t
This PR adds .satysfi-md file as one source of dependency graphs.
Meanwhile, lint subcommand still does not check dependencies of .satysfi-md files.
Resolves #205
> Support .satysfi-md as a source type of dependency graphs

- src/command/migrate.ml
- test/testcases/command_migrate__build_0_0_2.t
This PR has `migrate` command update OPAM files with an empty build section.
> Migrate: Add build section to OPAM files with an empty build section

- satyrographos.opam
I have found that the current description  `>= "0.13" && < "0.15"` of the dependency upon `core` seems probably incorrect, by getting the following error when trying to upgrade `satyrographos` to `0.0.2.8` (i.e. the latest version):
```console
#=== ERROR while compiling satyrographos.0.0.2.8 =====================#
```
This PR attempts to fix the constraint. According to the official documentation, `Core.Option.try_with_join` is available strictly since `0.14`, not since `0.13`:
* [0.13](https://ocaml.janestreet.com/ocaml-core/v0.13/doc/core_kernel/Core_kernel/Option/index.html)
* [0.14](https://ocaml.janestreet.com/ocaml-core/v0.14/doc/core_kernel/Core_kernel/Option/index.html)
Indeed, this modification seems to remedy the problem, as indicated by the success in `opam pin add …
> Fix the version constraint for 'core'

- .github/workflows/ci.yaml
cf. https://github.com/na4zagin3/satyrographos-repo/issues/256
> Don't build dependencies with tests or docs

- src/command/lint.ml
- src/command/lint_module_hashes.ml
- src/command/lint_problem.ml
- src/satysfi/version.ml
- test/testcases/command_lint__hash_font_src_dist.expected
- test/testcases/command_lint__hash_font_src_dist.ml
- test/testcases/dune
This adds a new lint warning `hash/font/location/src-dist` when `src-dist` field exists in a font entry in `fonts.satysfi-hash` or `mathfonts.satysfi-hash` for SATySFi 0.0.4 and later.
Related: https://github.com/na4zagin3/satyrographos/issues/10
> Add lint case hash/font/location/src-dist

- satyrographos.opam
This backports the patch at ocaml-repository: https://github.com/ocaml/opam-repository/pull/18283/commits/742fa570e95702501982885f5c8a439b75b8ae10
> Apply changes in opam-repository

- README-ja.md
- README.md
- I tried the command but it didn't work fine 😢 
```console
$ opam add -vy "file://$PWD"
opam: unknown command `add'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
$ opam add  --verbose --yes "file://$PWD"
opam: unknown command `add'.
Usage: opam COMMAND ...
Try `opam --help' for more information.
```
- As I'm not an expert of `opam` nor OCaml, I think it must be `opam pin add` 🤔 
- https://github.com/nyuichi/satysfi-base/blob/6c700c852be6e439b0860503e5134d19d7ff1ef3/.github/workflows/ci.yml#L20
> Fix opam command in README

- src/command/runSatysfi.ml
- src/satysfi/version.ml
- test/testcases/command_build__doc_satysfi.expected
- test/testcases/command_build__doc_satysfi.ml
- test/testcases/command_build__doc_with_autogen.expected
- test/testcases/command_build__doc_with_libraries.expected
- test/testcases/command_opam_build__doc_satysfi.expected
- test/testlib/prepareBin.ml
We can use --no-default-config option, which was introduced by
<https://github.com/gfngfn/SATySFi/pull/212>.
This fixes a problem where SATySFi may see stale `/usr/local/share/satysfi`.
> Use --no-default-config option

- src/command/migrate.ml
- test/testcases/command_migrate__build_0_0_2.t
Satyrographos migrate subcommand added a build section with a wrong module name,
which is suffixed by "satysfi-", while it should not be.
It also set a wrong task name to `satyrographos opam` subcommand.
> Fix a wrong name used in an added section by migrate

- README-ja.md
- README.md
It was changed as of eb83fdc1, but it was not reflected in `README.md`.
> README.md: `--package` -> `--library`

- bin/commandBuild.ml
- src/command/build.ml
- test/testcases/command_build__doc_make.expected
- test/testcases/command_build__doc_make.ml
- test/testcases/command_build__doc_satysfi.expected
- test/testcases/command_build__doc_satysfi.ml
- test/testcases/command_build__doc_with_autogen.expected
- test/testcases/command_build__doc_with_autogen.ml
- test/testcases/command_build__doc_with_libraries.expected
- test/testcases/command_build__doc_with_libraries.ml
This PR introduces two features to build subcommand:
- Accepting multiple module names.  If no module names are given, Satyrographos builds all the modules described in the Satyristes.
- Installing dependencies of doc module before building
> Install dependencies of doc module before building

- .github/workflows/ci.yaml
- SATySFi does not support OCaml 4.09 on CI so I drop this version
- https://github.com/gfngfn/SATySFi/blob/8a1b1fbefae9c6958d06ee64218619e00ef0afc7/.github/workflows/ci.yml#L12-L15
> Add newer version of OCaml

- .github/workflows/ci.yaml
- satyrographos.opam
This is an attempt to bring a feature of OCaml CI to detect problems before submitting the MR to opam-repository (v. https://github.com/ocaml/opam-repository/pull/20220).
Closes https://github.com/na4zagin3/satyrographos/issues/294
> Use ocaml-0install to test with minimal version sets

- src/command/install.ml
- src/library.ml
This commit handles a race-condition when non-dependent packages are being
removed during reading libraries.
> Catch all exceptions during reading libraries

- bin/commandLibrary.ml
Subcommand `library-opam list` originally output a list of packages with a OCaml
list format like `["dist"; "fss"]`.
This commit makes the output shellscript friendly--one line for each package
name-- like this:
```
dist
fss
```
> Make library-opam list subcommand output with lines

- test/testcases/command_new__doc_make.t
- test/testcases/command_new__doc_omake.t
- test/testcases/command_new__example_autogen.t
- test/testcases/dune
- test/testcases/test-utils.sh
This MR makes the cram test cases load shared shell functions.  It also makes testing Satyrographos libraries with `library-opam` subcommand instead of directly invoking `opam list` command.
> Refactor cram test cases with shell functions and library-opam list subcommand

- src/command/install.ml
- test/testcases/command_install__thirdParties_brokenDependency.expected
- test/testcases/command_install_l__thirdParties_brokenDependency.expected
This commit adds more information to error messages that reports missing dependencies.
Previous:
(Failure "Missing dependencies: (fonts-theano)")
Now:
(Failure "Missing dependencies: (fonts-theano). Revdeps: ((fonts-theano (grcnum)))")
> Install: show reverse dependencies of missing libraries
